#include "commands.h"
#include "cyfer.h"
#include "cyfer_utils.h"
#include "help.h"
#include "runners.h"

const Canonical cmds[] = {
    // RAW BYTES (non-interactive (CLI & Pipe) mode only)
    {
        .name    = "bytes2ascii",
        .from    = "Bytes",
        .to      = "ASCII",
        .aliases = {"byte2asc", "by2ac", "by2a"},
        .func    = run_bytes2ascii,
        .group   = "bytes",
        .prpt    = NULL,
    },
    {
        .name    = "bytes2decimal",
        .from    = "Bytes",
        .to      = "Decimal",
        .aliases = {"byte2dec", "by2dc", "by2d"},
        .func    = run_bytes2decimal,
        .group   = "bytes",
        .prpt    = NULL,
    },
    {
        .name    = "bytes2bits",
        .from    = "Bytes",
        .to      = "Bits",
        .aliases = {"byte2bit", "by2bi", "y2i"},
        .func    = run_bytes2bits,
        .group   = "bytes",
        .prpt    = NULL,
    },
    {
        .name    = "bytes2hex",
        .from    = "Bytes",
        .to      = "Hex",
        .aliases = {"byte2hex", "by2hx", "by2h"},
        .func    = run_bytes2hex,
        .group   = "bytes",
        .prpt    = NULL,
    },
    {
        .name    = "bytes2base64",
        .from    = "Bytes",
        .to      = "Base64",
        .aliases = {"byte2base", "by2b64", "by2b6"},
        .func    = run_bytes2base64,
        .group   = "bytes",
        .prpt    = NULL,
    },
    // ASCII
    {
        .name    = "ascii2bytes",
        .from    = "ASCII",
        .to      = "Bytes",
        .aliases = {"asc2byte", "ac2by", "a2by"},
        .func    = run_ascii2bytes,
        .group   = "ascii",
        .prpt    = NULL,
    },
    {
        .name    = "ascii2decimal",
        .from    = "ASCII",
        .to      = "Decimal",
        .aliases = {"asc2dec", "ac2dc", "a2d"},
        .func    = run_ascii2decimal,
        .group   = "ascii",
        .prpt    = prpt_ascii,
    },
    {
        .name    = "ascii2bits",
        .from    = "ASCII",
        .to      = "Bits",
        .aliases = {"asc2bit", "ac2bi", "a2bi"},
        .func    = run_ascii2bits,
        .group   = "ascii",
        .prpt    = prpt_ascii,
    },
    {
        .name    = "ascii2hex",
        .from    = "ASCII",
        .to      = "Hex",
        .aliases = {"asc2hex", "ac2hx", "a2h"},
        .func    = run_ascii2hex,
        .group   = "ascii",
        .prpt    = prpt_ascii,
    },
    {
        .name    = "ascii2base64",
        .from    = "ASCII",
        .to      = "Base64",
        .aliases = {"asc2b64", "ac2b6", "a2b6"},
        .func    = run_ascii2base64,
        .group   = "ascii",
        .prpt    = prpt_ascii,
    },
    // Decimal
    {
        .name    = "decimal2bytes",
        .from    = "Decimal",
        .to      = "Bytes",
        .aliases = {"dec2byte", "dc2by", "d2by"},
        .func    = run_decimal2bytes,
        .group   = "decimal",
        .prpt    = NULL,
    },
    {
        .name    = "decimal2ascii",
        .from    = "Decimal",
        .to      = "ASCII",
        .aliases = {"dec2asc", "dc2ac", "d2a"},
        .func    = run_decimal2ascii,
        .group   = "decimal",
        .prpt    = prpt_decimal,
    },
    {
        .name    = "decimal2bits",
        .from    = "Decimal",
        .to      = "Bits",
        .aliases = {"dec2bit", "dc2bi", "d2bi"},
        .func    = run_decimal2bits,
        .group   = "decimal",
        .prpt    = prpt_decimal,
    },
    {
        .name    = "decimal2hex",
        .from    = "Decimal",
        .to      = "Hex",
        .aliases = {"dec2hex", "dc2hx", "d2h"},
        .func    = run_decimal2hex,
        .group   = "decimal",
        .prpt    = prpt_decimal,
    },
    {
        .name    = "decimal2base64",
        .from    = "Decimal",
        .to      = "Base64",
        .aliases = {"dec2b64", "dc2b6", "d2b6"},
        .func    = run_decimal2base64,
        .group   = "decimal",
        .prpt    = prpt_decimal,
    },
    // Bits
    {
        .name    = "bits2bytes",
        .from    = "Bits",
        .to      = "Bytes",
        .aliases = {"bit2byte", "bi2by", "i2y"},
        .func    = run_bits2bytes,
        .group   = "bits",
        .prpt    = NULL,
    },
    {
        .name    = "bits2ascii",
        .from    = "Bits",
        .to      = "ASCII",
        .aliases = {"bit2ascii", "bit2asc", "bi2a"},
        .func    = run_bits2ascii,
        .group   = "bits",
        .prpt    = prpt_bit,
    },
    {
        .name    = "bits2decimal",
        .from    = "Bits",
        .to      = "Decimal",
        .aliases = {"bit2dec", "bi2dc", "bi2d"},
        .func    = run_bits2decimal,
        .group   = "bits",
        .prpt    = prpt_bit,
    },
    {
        .name    = "bits2hex",
        .from    = "Bits",
        .to      = "Hex",
        .aliases = {"bit2hex", "bi2hx", "bi2h"},
        .func    = run_bits2hex,
        .group   = "bits",
        .prpt    = prpt_bit,
    },
    {
        .name    = "bits2base64",
        .from    = "Bits",
        .to      = "Base64",
        .aliases = {"bit2b64", "bi2b6", "bi2ba"},
        .func    = run_bits2base64,
        .group   = "bits",
        .prpt    = prpt_bit,
    },
    // Hex
    {
        .name    = "hex2bytes",
        .from    = "Hex",
        .to      = "Bytes",
        .aliases = {"hex2byte", "hx2by", "h2by"},
        .func    = run_hex2bytes,
        .group   = "hex",
        .prpt    = NULL,
    },
    {
        .name    = "hex2ascii",
        .from    = "Hex",
        .to      = "ASCII",
        .aliases = {"hex2asc", "hx2ac", "h2a"},
        .func    = run_hex2ascii,
        .group   = "hex",
        .prpt    = prpt_hex,
    },
    {
        .name    = "hex2decimal",
        .from    = "Hex",
        .to      = "Decimal",
        .aliases = {"hex2dec", "hx2dc", "h2d"},
        .func    = run_hex2decimal,
        .group   = "hex",
        .prpt    = prpt_hex,
    },
    {
        .name    = "hex2bits",
        .from    = "Hex",
        .to      = "Bits",
        .aliases = {"hex2bit", "hx2bi", "h2bi"},
        .func    = run_hex2bits,
        .group   = "hex",
        .prpt    = prpt_hex,
    },
    {
        .name    = "hex2base64",
        .from    = "Hex",
        .to      = "Base64",
        .aliases = {"hex2b64", "hx2b6", "h2b6"},
        .func    = run_hex2base64,
        .group   = "hex",
        .prpt    = prpt_hex,
    },
    // Base64
    {
        .name    = "base642bytes",
        .from    = "Base64",
        .to      = "Bytes",
        .aliases = {"base2byte", "b642by", "b62by"},
        .func    = run_base642bytes,
        .group   = "base64",
        .prpt    = NULL,
    },
    {
        .name    = "base642ascii",
        .from    = "Base64",
        .to      = "ASCII",
        .aliases = {"b642asc", "b62ac", "b62a"},
        .func    = run_base642ascii,
        .group   = "base64",
        .prpt    = prpt_base64,
    },
    {
        .name    = "base642decimal",
        .from    = "Base64",
        .to      = "Decimal",
        .aliases = {"b642dec", "b62dc", "b62d"},
        .func    = run_base642decimal,
        .group   = "base64",
        .prpt    = prpt_base64,
    },
    {
        .name    = "base642bits",
        .from    = "Base64",
        .to      = "Bits",
        .aliases = {"b642bit", "b62bi", "ba2bi"},
        .func    = run_base642bits,
        .group   = "base64",
        .prpt    = prpt_base64,
    },
    {
        .name    = "base642hex",
        .from    = "Base64",
        .to      = "Hex",
        .aliases = {"b642hex", "b62hx", "b62h"},
        .func    = run_base642hex,
        .group   = "base64",
        .prpt    = prpt_base64,
    },
    // Auto convert mode
    {
        .name    = "auto-detect",
        .from    = "any",
        .to      = "representations",
        .aliases = {"auto", "detect", "d"},
        .func    = run_detect,
        .group   = "detect",
        .prpt    = NULL
    },
    // help
    {
        .name    = "--help",
        .from    = NULL,
        .to      = NULL,
        .aliases = {"--hlp", "-h", "?"},
        .func    = help_cmd,
        .group   = "help",
        .prpt    = NULL,
    },
    // modes & aliases
    {
        .name    = "--converters",
        .from    = NULL,
        .to      = NULL,
        .aliases = {"--cvts", "--cvt", "-c"},
        .func    = list_converters_cmd,
        .group   = "converter",
        .prpt    = NULL,
    },
    {
        .name    = "--aliases",
        .from    = NULL,
        .to      = NULL,
        .aliases = {"--alias", "--als", "-a"},
        .func    = list_aliases_cmd,
        .group   = "alias",
        .prpt    = NULL,
    },
};

const size_t cmds_count = sizeof(cmds) / sizeof(cmds[0]);
// converters_count = cmds_count - (list_converters_cmd + list_aliases_cmd + auto_detect_cmd)
const size_t converters_count = sizeof(cmds) / sizeof(cmds[0]) - 3;

